# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@1
  inputs:
    mavenPomFile: 'spring-boot-docker/pom.xml'
    mavenOptions: '-Xmx3072m'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    goals: 'package'
- task: Maven@4
  inputs:
    mavenPomFile: '''$(System.DefaultWorkingDirectory)/spring-boot-docker/pom.xml'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

