# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: mavenbuildjob
    jobs:
      - job: mavenbuildjob
        continueOnError: false
        steps:
        - task: CmdLine@2
          inputs:
            script: 'ls -al'
        - task: JavaToolInstaller@0
          inputs:
            versionSpec: '17'
            jdkArchitectureOption: 'x64'
            jdkSourceOption: 'PreInstalled'
        - task: Maven@4
          inputs:
            mavenPomFile: 'pom.xml'
            publishJUnitResults: false
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false
        - task: Docker@2
          inputs:
            containerRegistry: 'docker-svc-con'
            repository: 'abdulregistry/spring-boot-docker-example'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'
            tags: v2.$(Build.BuildId)